import tkinter as tk
from tkinter import ttk, messagebox
import threading
import sys
import os
import io
import numpy as np
from contextlib import redirect_stdout

# ============================================================================
# CONFIGURATION: PATHS TO YOUR SIMULATION SCRIPTS
# ============================================================================
PL_PATH = r"C:\Users\liam\Documents\GitHub\all-of-my-code\sportsanalysis\premier-league"
NLN_PATH = r"C:\Users\liam\Documents\GitHub\all-of-my-code\sportsanalysis\darlington"

# Map display names to (directory_path, module_filename)
LEAGUE_CONFIGS = {
    "Premier League 26/27": (PL_PATH, "26-27-season.py"),
    "National League North 25/26": (NLN_PATH, "nationleague.py"),
}


class SimulationWorker(threading.Thread):
    """Runs the simulation in a background thread and captures stdout."""

    def __init__(self, league_key, callback):
        super().__init__(daemon=True)
        self.league_key = league_key
        self.callback = callback
        self.output = ""
        self.error = None

    def run(self):
        try:
            dir_path, filename = LEAGUE_CONFIGS[self.league_key]
            module_name = filename.replace(".py", "")

            # Add directory to path temporarily for import
            if dir_path not in sys.path:
                sys.path.insert(0, dir_path)

            # Capture stdout generated by print() statements in the sim
            f = io.StringIO()
            with redirect_stdout(f):
                # Import and execute main()
                # We use importlib to handle hyphens in filenames like '26-27-season'
                import importlib.util
                spec = importlib.util.spec_from_file_location(module_name, os.path.join(dir_path, filename))
                mod = importlib.util.module_from_spec(spec)
                
                # Prevent the script's `if __name__ == "__main__"` guard from blocking
                # by directly calling main() after loading
                spec.loader.exec_module(mod)
                
                if hasattr(mod, "main"):
                    mod.main()
                else:
                    raise AttributeError(f"No main() function found in {filename}")

            self.output = f.getvalue()

        except Exception as e:
            self.error = str(e)
        finally:
            # Clean up sys.path
            if dir_path in sys.path:
                sys.path.remove(dir_path)

        # Schedule UI update on main thread
        self.callback(self.output, self.error)


class LeaguePredictorGUI:
    def __init__(self, root):
        self.root = root
        self.root.title("Football League Predictor")
        self.root.geometry("1100x750")
        self.root.minsize(900, 600)

        # Style setup
        style = ttk.Style()
        style.theme_use("clam")
        style.configure("Treeview", rowheight=25, font=("Consolas", 10))
        style.configure("Treeview.Heading", font=("Segoe UI", 10, "bold"))
        style.configure("Run.TButton", font=("Segoe UI", 11, "bold"), padding=10)

        # --- Top Control Frame ---
        ctrl_frame = ttk.Frame(root, padding=10)
        ctrl_frame.pack(fill=tk.X)

        ttk.Label(ctrl_frame, text="Select League:", font=("Segoe UI", 11)).pack(side=tk.LEFT, padx=(0, 5))
        self.league_var = tk.StringVar(value=list(LEAGUE_CONFIGS.keys())[0])
        self.league_combo = ttk.Combobox(
            ctrl_frame, textvariable=self.league_var,
            values=list(LEAGUE_CONFIGS.keys()), state="readonly", width=30
        )
        self.league_combo.pack(side=tk.LEFT, padx=(0, 15))

        self.run_btn = ttk.Button(
            ctrl_frame, text="▶ Run Simulation", style="Run.TButton",
            command=self.start_simulation
        )
        self.run_btn.pack(side=tk.LEFT)

        self.status_label = ttk.Label(ctrl_frame, text="Ready", foreground="gray")
        self.status_label.pack(side=tk.RIGHT)

        # --- Notebook for Table + Raw Output ---
        self.notebook = ttk.Notebook(root)
        self.notebook.pack(fill=tk.BOTH, expand=True, padx=10, pady=(0, 10))

        # Tab 1: Parsed League Table
        table_frame = ttk.Frame(self.notebook)
        self.notebook.add(table_frame, text="📊 Predicted Table")

        cols = ("Pos", "Team", "P", "W", "D", "L", "GF", "GA", "GD", "Pts", "ELO")
        self.tree = ttk.Treeview(table_frame, columns=cols, show="headings", selectmode="browse")
        for col in cols:
            anchor = tk.CENTER if col != "Team" else tk.W
            width = 180 if col == "Team" else 55
            self.tree.heading(col, text=col, anchor=anchor)
            self.tree.column(col, width=width, anchor=anchor, minwidth=40)

        vsb = ttk.Scrollbar(table_frame, orient=tk.VERTICAL, command=self.tree.yview)
        hsb = ttk.Scrollbar(table_frame, orient=tk.HORIZONTAL, command=self.tree.xview)
        self.tree.configure(yscrollcommand=vsb.set, xscrollcommand=hsb.set)

        self.tree.grid(row=0, column=0, sticky="nsew")
        vsb.grid(row=0, column=1, sticky="ns")
        hsb.grid(row=1, column=0, sticky="ew")
        table_frame.rowconfigure(0, weight=1)
        table_frame.columnconfigure(0, weight=1)

        # Tag styles for color coding
        self.tree.tag_configure("champion", background="#d4edda", foreground="#155724")
        self.tree.tag_configure("ucl", background="#cce5ff", foreground="#004085")
        self.tree.tag_configure("europa", background="#fff3cd", foreground="#856404")
        self.tree.tag_configure("playoff", background="#e2e3f1", foreground="#383d6e")
        self.tree.tag_configure("relegated", background="#f8d7da", foreground="#721c24")
        self.tree.tag_configure("safe", background="#ffffff")

        # Tab 2: Raw Console Output
        raw_frame = ttk.Frame(self.notebook)
        self.notebook.add(raw_frame, text="🖥️ Raw Output")

        self.raw_text = tk.Text(raw_frame, wrap=tk.NONE, font=("Consolas", 9), bg="#1e1e1e", fg="#d4d4d4")
        raw_vsb = ttk.Scrollbar(raw_frame, orient=tk.VERTICAL, command=self.raw_text.yview)
        raw_hsb = ttk.Scrollbar(raw_frame, orient=tk.HORIZONTAL, command=self.raw_text.xview)
        self.raw_text.configure(yscrollcommand=raw_vsb.set, xscrollcommand=raw_hsb.set)
        self.raw_text.grid(row=0, column=0, sticky="nsew")
        raw_vsb.grid(row=0, column=1, sticky="ns")
        raw_hsb.grid(row=1, column=0, sticky="ew")
        raw_frame.rowconfigure(0, weight=1)
        raw_frame.columnconfigure(0, weight=1)

        # Store last parsed data
        self.last_table_data = []

    def start_simulation(self):
        self.run_btn.config(state=tk.DISABLED)
        self.status_label.config(text="⏳ Simulating... (this may take a minute)", foreground="orange")
        self.raw_text.delete("1.0", tk.END)

        # Clear previous table
        for item in self.tree.get_children():
            self.tree.delete(item)

        worker = SimulationWorker(self.league_var.get(), self.on_simulation_complete)
        worker.start()

    def on_simulation_complete(self, output, error):
        """Called on main thread after simulation finishes."""
        self.run_btn.config(state=tk.NORMAL)

        if error:
            self.status_label.config(text="❌ Error", foreground="red")
            self.raw_text.insert(tk.END, f"ERROR: {error}\n")
            messagebox.showerror("Simulation Error", error)
            return

        self.status_label.config(text="✅ Complete", foreground="green")
        self.raw_text.delete("1.0", tk.END)
        self.raw_text.insert(tk.END, output)

        # Parse the table from output
        rows = self._parse_table(output)
        if rows:
            self._populate_table(rows)
            self.notebook.select(0)  # Switch to table tab
        else:
            self.status_label.config(text="⚠️ Done but couldn't parse table", foreground="orange")
            self.notebook.select(1)  # Switch to raw output tab

    def _parse_table(self, output: str) -> list[dict]:
        """
        Parse league table rows from raw simulation output.
        Handles both PL and NLN formats by looking for numeric patterns.
        """
        rows = []
        lines = output.strip().split("\n")
        in_table = False

        for line in lines:
            stripped = line.strip()
            # Detect table header or separator lines
            if stripped.startswith("---") or stripped.startswith("==="):
                continue
            if "Pos" in stripped and "Team" in stripped and "Pts" in stripped:
                in_table = True
                continue
            if not in_table:
                continue
            if not stripped or stripped.startswith("="):
                if rows:  # End of table block
                    break
                continue

            # Try to parse a data row
            parts = stripped.split()
            if len(parts) < 8:
                continue

            try:
                pos = int(parts[0])
                # Find where numeric stats start after team name
                # Team name can be multi-word; scan from right for known stat count
                # Expected: P W D L GF GA GD Pts [ELO] [Status...]
                # Work backwards from end to find stats
                numeric_parts = []
                idx = len(parts) - 1
                while idx > 0:
                    try:
                        float(parts[idx].replace("+", "").replace("-", ""))
                        numeric_parts.insert(0, parts[idx])
                        idx -= 1
                    except ValueError:
                        break

                if len(numeric_parts) >= 8:
                    team_name = " ".join(parts[1:idx + 1])
                    p = int(numeric_parts[0])
                    w = int(numeric_parts[1])
                    d = int(numeric_parts[2])
                    l = int(numeric_parts[3])
                    gf = int(numeric_parts[4])
                    ga = int(numeric_parts[5])
                    gd_str = numeric_parts[6]
                    gd = int(gd_str.replace("+", ""))
                    pts = int(numeric_parts[7])
                    elo = float(numeric_parts[8]) if len(numeric_parts) > 8 else 0.0

                    # Check for status text at end
                    status = ""
                    remaining = parts[idx + 1 + len(numeric_parts):]
                    if remaining:
                        status = " ".join(remaining)

                    rows.append({
                        "pos": pos, "team": team_name, "p": p, "w": w, "d": d,
                        "l": l, "gf": gf, "ga": ga, "gd": gd, "pts": pts,
                        "elo": round(elo, 1), "status": status.upper()
                    })
            except (ValueError, IndexError):
                continue

        return sorted(rows, key=lambda r: (-r["pts"], -r["gd"], -r["gf"]))

    def _populate_table(self, rows: list[dict]):
        for item in self.tree.get_children():
            self.tree.delete(item)

        n_teams = len(rows)
        for row in rows:
            tag = self._get_row_tag(row, n_teams)
            gd_display = f"+{row['gd']}" if row['gd'] > 0 else str(row['gd'])
            values = (
                row["pos"], row["team"], row["p"], row["w"], row["d"],
                row["l"], row["gf"], row["ga"], gd_display, row["pts"], row["elo"]
            )
            self.tree.insert("", tk.END, values=values, tags=(tag,))

    def _get_row_tag(self, row: dict, n_teams: int) -> str:
        """Determine color tag based on position/status."""
        status = row.get("status", "")
        pos = row["pos"]

        if "CHAMPION" in status or "PROMOTED" in status:
            return "champion"
        if "PLAYOFF" in status:
            return "playoff"
        if "RELEGAT" in status:
            return "relegated"

        # Fallback positional coloring
        if n_teams == 20:  # Premier League
            if pos == 1:
                return "champion"
            if pos <= 4:
                return "ucl"
            if pos == 5:
                return "europa"
            if pos >= 18:
                return "relegated"
        elif n_teams == 24:  # National League
            if pos == 1:
                return "champion"
            if 2 <= pos <= 7:
                return "playoff"
            if pos >= 21:
                return "relegated"

        return "safe"


def main():
    root = tk.Tk()
    app = LeaguePredictorGUI(root)
    root.mainloop()


if __name__ == "__main__":
    main()